### ISSUE TITLE
Add text length limit on TextBox control

### ISSUE THREAD

**Issue by okonk** [billyquith/GWork#50]
Hi, I'd like to add a text length limit to the TextBox control, but I see there's a few possible complications here.

1. Where to do the change? I think doing it on the TextBox control makes the most sense since the purpose of this limit is to limit the amount of text a user can enter.

2. Naming of things relating to the limit. Do you have a preferred name? Right now I'm using SetMaxTextLength/GetMaxTextLength/m_maxTextLength.

3. What should the behaviour be when editing text and the cursor isn't at the end? For example suppose the limit is set to 5. The current text is "12345" and the cursor is between the 3 and 4. Now you type 'a'. What is the result? Is it "12345" since the limit is met and you can't add any more text? Is it "123a4" bumping the 5 off the end?

4. Similar scenario to the above, but instead 4 is highlighted. Your clipboard contains "ab" and you paste. What is the result? "12345"? "123ab"? 

5. As above in 4, but what if the clipboard only contained 'a'?

6. Should the limit apply to the subclasses of TextBox? If this applies to TextBoxMultiline, should the '\n' characters count towards the limit? For ease of implementation I would probably just say yes it should apply to subclasses, and newlines do count towards the limit.

Thinking about it some more, questions 3-5 come down to the behavior of should the limit be the limit and if the user wants to insert in the middle they have to take characters off the end first? Or if you insert in the middle should it bump characters off the end?

I just did a quick test with an HTML input box ([jsfiddle](https://jsfiddle.net/5pnnpzzx/)) and essentially the limit is the limit. It doesn't do any bumping.

Am I missing anything else?

**Comment by okonk** [comment]
To be clearer, with HTML input box:
Trying to insert into the middle doesn't allow it, so the result is "12345".
Trying to paste multiple chars over a selected char pastes one, so the result is "123a5".
Pasting one character over a selected char is allowed. Result "123a5".

I think GWork should emulate this behaviour.

**Comment by eXpl0it3r** [comment]
Not involved that much in the project, but here's just my opinion on some of the points.

For 2: I could also see SetMaxLength without "text", then again it might be slightly ambiguous regarding the size of the text box.

For 3-5: Don't invent any new behavior. Overriding/bumping text doesn't really make sense. If the text box contains the max amount of letters, you just can't add more. If you highlight a letter and override it with your clipboards contents it just replaced the selected text until the text box is full again.

For 6: New lines should count, otherwise you can just fill a multiline text box with new lines and it will never be limited.

**Comment by billyquith** [comment]
Another problem might be truncating a UTF8 string.

**Comment by billyquith** [comment]
I think this thread is finished. If there are any new issues then please open a new ticket specific to the issue.
